version: "3.9"
networks:
  auth:
    driver: bridge

services:
  app:
    container_name: AuthService
    hostname: auth-service
    image: ywkbm/auth:latest
    ports:
      - "${PORT}:${PORT}"
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      SECRET_KEY: ${SECRET_KEY}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      SSL_MODE: ${SSL_MODE}
      DB_PORT: ${DB_PORT}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      RABBIT_URL: ${RABBIT_URL}
      LOGIN: ${LOGIN}
      PASSWORD: ${PASSWORD}
      EMAIL: ${EMAIL}
    networks:
      - auth
