-- +goose Up
CREATE TABLE users
(
  Id SERIAL PRIMARY KEY,
  Login TEXT NOT NULL,
  Password TEXT NOT NULL,
  UserRole TEXT NOT NULL,
  Email TEXT NOT NULL
);

CREATE TABLE userToken
(
  Id SERIAL PRIMARY KEY,
  Jti TEXT NOT NULL,
  UserId INT NOT NULL REFERENCES users (Id),
  Expiry TIMESTAMPTZ NOT NULL
);